#!/bin/bash
if [ -z "$VIRTUAL_ENV" ]; then
    echo "You should activate the virtualenv before running this command."
    echo "$ source venv/bin/activate"
    exit 1
fi
ROOT=`pwd`
for REPO in ranker srcomp srcomp-http
do
    cd $ROOT/$REPO
    python setup.py test
done

