#!/bin/sh

me=`readlink -e $0`
my_dir=`dirname $me`

for rt in `find -name run-tests`
do
    the_dir=`dirname $rt`
    echo Testing $the_dir
    cd $the_dir
    ./run-tests
    if [ $? -ne 0 ]
    then
        echo Failures in $the_dir, aborting
        exit 1
    fi
    cd $my_dir
done
echo Yay, all tests pass
